image: python:3.7
stages:
  - test

.python_job_template: &python_job_definition
  image: python:3.7
  stage: test
  before_script:
    - 'python3 -m pip install wheel'
    - 'python3 -m pip install --upgrade pip --force'

lint-python:
  <<: *python_job_definition
  script:
    - 'python3 -m pip install flake8'
    - 'python3 -m flake8 --statistics --show-source --max-line-length=120'

unit-tests-python:
  <<: *python_job_definition
  script:
    - 'python3 -m pip install -r requirements.txt'
    - 'python3 -m pip install -r requirements-dev.txt'
    - 'python3 -m pytest ./tests'
